### ISSUE TITLE
Helm 3 removed Tiller

### ISSUE THREAD

**Issue by maui1911** [kerberos-io/enterprise#1]
Trying to install Kerberos Enterprise on a local Kubenetes cluster, but i'm stuck @ tiller install.

more info: https://helm.sh/docs/faq/#removal-of-tiller

**Comment by cedricve** [comment]
thanks for reporting, we didnt tried helm 3 so far. So not sure if you find a workaround, glad to help. I expect some details might change in that case.

**Comment by cedricve** [comment]
documentation was updated to support helm3 .
