### ISSUE TITLE
Request to open source docker image code

### ISSUE THREAD

**Issue by jnaulty** [kerberos-io/enterprise#4]
Would it be possible to publish the necessary repositories to build the docker images used in the cluster that come from kerberos, specifically: `kerberos/enterprise-machinery` and `kerberos/enterprise-factory`. 

I like to build, sign, and host the images used in the clusters I run, and would like to do the same for kerberos enterprise.

**Comment by cedricve** [comment]
We will not make those Docker images or source available, however our Kerberos Open Source will migrate to a very similar code stack.  https://github.com/kerberos-io/opensource
