### ISSUE TITLE
New Deployments not created

### ISSUE THREAD

**Issue by JBFUK** [kerberos-io/enterprise#5]
I've installed the system as described here:

https://doc.kerberos.io/enterprise/installation-edge

Once logged in I try to add a new deployment.  I click on 'Add+', in the popup I enter a name and the rtsp URL for the video stream.  It seems to be accepted when I click on 'Add' button to complete, the window closes but nothing happens.

It's also quite annoying that the name cannot contain numbers or spaces but that's a minor issue.

**Comment by cedricve** [comment]
hey @JBFUK thanks for reporting. These could mean two things.

1. have you enabled RBAC? What this is doing, is trying to create a deployment and thus pod in your cluster.

2. Can you verify the connection with mongodb is working and if the configuration has been created in the KerberosFactory database.

**Comment by JBFUK** [comment]
Well I followed the guide linked to above, step by step, and everything seemed to work until I attempted to add cameras.  I believe enabling RBAC is one of the steps in the guide.

I rebooted the kubernetes host to see whether it would get things working but it's completely broken, I can't even use kubectl without an error - totally dead.  Kubernetes is new to me.  I liked the idea of having some resilience in my CCTV but this all seems too complicated and time consuming for a few home security cameras. 

Have switched to trying out the opensource version running with docker instead.  Looking forward to what's going to be uploaded to the 'hub' repository.

**Comment by cedricve** [comment]
@JBFUK  hey there, I agree Kerberos Enterprise requires a proficient level of Kubernetes. Might be interesting but we are revamping the open source part, this will contain a complete new UI and functionalities (v3). However this is not yet released, so for the time being it should be (v2) that you should use.

**Comment by JBFUK** [comment]
Will the v3 include the single pane of glass for multiple devices?

**Comment by cedricve** [comment]
That will be Kerberos Hub ;) It will allow you to add Kerberos Open Source instances (eithrr being it docker containers and radpberry pi's). Hub will call the different API's from kerberos open source and show the recordings and other settings inside a single interface. This doesnt bring complexity for basic users with only single instance, and allow people with multiple instances to have more flexibility. Overall this  Hub approach is the best for our architectural design: keep everything isolated, if a camera fails for some reason other cameras are not affected.

**Comment by cedricve** [comment]
@JBFUK, are you using capitals in the camera names?

**Comment by JBFUK** [comment]
Do couldn't say what I tried for sure now, but probably yes.

**Comment by ducthinh993** [comment]
Hello guys,
Same here. I was able to add a camera on the UI but the log shows:
```
[GIN] 2021/05/01 - 08:22:59 | 400 |   32.867395ms |    x.x.x.x | POST     /kubernetes/deployment
[GIN] 2021/05/01 - 08:22:59 | 400 |   32.900314ms |    x.x.x.x | POST     /kubernetes/deployment
```
I checked the MongoDB connection. Kerberos was successful in create collection `configuration`

**Comment by cedricve** [comment]
@ducthinh993 can you provide more details about the camera name etc.

**Comment by cedricve** [comment]
This typically happens when entering capitals in the UI. We are making a new big release, new UI changes, better testing, etc.
