### ISSUE TITLE
How do you specify the namespace to deploy for machinery?

### ISSUE THREAD

**Issue by dmnt3d** [kerberos-io/enterprise#8]
When adding new camera, machinery pods gets deployed in default namespace which causes the application to fail since i have the kerberos enterprise deployed on a specific namespace.

Is there a way to specify which namespace it will be deployed?

**Comment by cedricve** [comment]
valid point! will provide a fix for that this evening! Will provide an environment variable for that in the enterprise deployment.

Kind regards,
Verstraeten Cédric

**Comment by cedricve** [comment]
This is fixed. In latest documentations
