### ISSUE TITLE
Traefik External IP pending

### ISSUE THREAD

**Issue by itsphilctrl** [kerberos-io/enterprise#9]
Hi

Relatively new to Kubernetes and brand new to kerberos.io so please bare with me.

I have been following this guide (number of times) after deploying a new kubernetes cluster. Obviously starting after kubernetes steps. https://doc.kerberos.io/enterprise/installation-edge

All goes well until I user this command.

kubectl apply -n kerberos -f ./enterprise/yaml/metallb/configmap.yaml

I get the following error returned.

error: the namespace from the provided object "metallb-system" does not match the namespace "kerberos". You must pass '--namespace=metallb-system' to perform this operation.

Reading the error I have tried changing the command to 

kubectl apply -n metallb-system -f ./enterprise/yaml/metallb/configmap.yaml

This time the command is accepted and I can then continue with installation. 

Once Helm is installed I check progress

kubectl get svc traefik --namespace kerberos -w

NAME      TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
traefik   LoadBalancer   10.101.63.170   <pending>     443:30557/TCP,80:31194/TCP   4m52s

I can see that the external IP is pending, I know this can take time to be assigned but further checks over the course of 15 min show pending. 

Figuring I have made an error during deployment so I revert to prior snapshot and restart kerberos.io deployment.

Prior to the command in question, I edit the ./enterprise/yaml/metallb/configmap.yaml setting the namespace to kerberos along with changing the IPs made last time..

This time this command completes OK.

kubectl apply -n kerberos -f ./enterprise/yaml/metallb/configmap.yaml

Continue with install and after helm completes I check status.

kubectl get svc traefik --namespace kerberos -w

Again I see the external IP is pending.

What i missing? I am sure it will be obvious to someone. Any guidance really appreciated.

**Comment by itsphilctrl** [comment]
working. correct command was 

kubectl get svc traefik --namespace kerberos -w

no idea why this did not work on previous attempts.

**Comment by cedricve** [comment]
Docs were updated regarding this.
